### ISSUE TITLE
first-person camera in 3d hack produces glitches when avatar's mesh is empty or a billboard

### ISSUE THREAD

**Issue by aloelazoe** [seleb/bitsy-hacks#104]
this is most noticeable when standing in the corner and turning. sometimes glitches appear when there is another room being rendered below the current room
there are no glitches when avatar's mesh is plane/box/wedge/tower though
perhaps would make sense to change the default mesh for avatar back to plane so that people who start using first-person camera with the default setup wouldn't run into it

**Comment by seleb** [comment]
can you clarify what the glitches are that this config is causing? tried to reproduce it and things seemed fine with the player as a billboard, but i'm not sure what i'm looking for

**Comment by aloelazoe** [comment]
hm.. they show up with a pretty simple setup like this, just the room with towers 5 units below and a walkable room above it
[camera_glitch_test.html.zip](https://github.com/seleb/bitsy-hacks/files/3457411/camera_glitch_test.html.zip)

**Comment by aloelazoe** [comment]
and with the corners... glitches appear when just turnining in different directions on the starting tile
[camera_glitch_test_corners.html.zip](https://github.com/seleb/bitsy-hacks/files/3457466/camera_glitch_test_corners.html.zip)

**Comment by aloelazoe** [comment]
just tested in two other browsers.. it's very peculiar, these glitches only appear in chrome and firefox but everything is fine in safari

**Comment by seleb** [comment]
can you be more specific about what the glitches are that you're seeing? i've tested on chrome, firefox, and opera without any apparent issue in either of those files. it's possible i'm just missing something, but i would guess it's actually not reproducing for me. could you post a gif or a video maybe?

**Comment by aloelazoe** [comment]
sure!
https://imgur.com/a/AIvVc5H

**Comment by seleb** [comment]
oh woah yeah i'm definitely not seeing that behaviour; k i'm putting the default back to plane as suggested. not sure what's actually going on there, will need to investigate further

**Comment by seleb** [comment]
closing as i have no plans on updating the 3d hack (see [bitsy 3d](https://aloelazoe.itch.io/bitsy-3d))
