### ISSUE TITLE
Add tests to hacks

### ISSUE THREAD

**Issue by seleb** [seleb/bitsy-hacks#148]
A bunch of the more frequently used or recently added hacks have tests, but it would be good to get some coverage on more of them since the tests are the easiest way to catch compatibility issues when bitsy updates.

- [x] avatar by room
- [x] basic sfx
- [x] bitsymuse
- [x] canvas replacement
- [x] character portraits animated
- [x] character portraits
- [x] close on ending
- [x] corrupt
- [x] custom text effect
- [x] custom-exit-effects
- [x] custom-keyhandlers
- [x] dialog audio vocal synth
  - how to test sound?
- [x] dialog audio
  - how to test sound?
- [x] dialog box transition
- [x] dialog choices
- [x] dialog jump
- [x] dialog pause
- [x] dialog prompt
- [x] direction in dialog
- [x] directional avatar
- [x] dynamic background
- [x] edit dialog from dialog
- [x] edit image from dialog
- [x] edit room from dialog
- [x] end-from-dialog
- [x] exit-from-dialog
- [x] external-game-data
- [x] favicon-from-sprite
- [x] follower
- [x] gamepad input
- [x] gravity
- [x] itsy-bitsy
- [x] javascript dialog
- [x] logic-operators-extended
- [x] long dialog
- [x] multi-sprite avatar
- [x] noclip
- [x] online
  - is it even reasonable to try to test online integration?
- [x] opaque tiles
- [x] paragraph-break
- [x] permanent items
- [x] push-sprites
- [x] replace drawing
- [x] save
- [x] smooth moves
  - difficult due to async
- [x] solid items
- [x] stopwatch
- [x] text-to-speech
- [x] tracery processing
- [x] transitions
- [x] transparent dialog
- [x] transparent sprites
- [x] twine-bitsy-comms
  - is it even reasonable to try to test twine integration?
- [x] unique items

**Comment by metaleptic** [comment]
Hi there!
I kind of wrote you an email about certain limits I was reaching earlier, and I just saw this "help wanted" tag. I'm game, if you need help for testing stuff! :)

**Comment by seleb** [comment]
hey @metaleptic, yeah if you want to take a stab at adding some tests, feel free to tackle any of the unchecked things on this list!

**Comment by seleb** [comment]
all tests have at least basic coverage now; there are definitely things they wont catch, but should be good enough to catch anything that totally breaks on bitsy updates!
