### ISSUE TITLE
Opaque tiles do not work in 7.2

### ISSUE THREAD

**Issue by Zverik** [seleb/bitsy-hacks#166]
Tried to use opaque tiles hack in my game and found out it doesn't work. When I step on an opaque tile, the avatar indeed disappears. But movement stops working as well.

Example (default game, blocks are opaque): http://textual.ru/opaque_fail.html

When testing, I found out the `before drawRoom()` function gets called twice for every movement. First time the `room` variable is set correctly, and the second time it's rewritten with `null`.

**Comment by seleb** [comment]
tested this out, and it looks like the problem is actually how you've copy-pasted the hack: it's been pasted inside an existing `<script>` tag in the exported game, rather than in a new one at the bottom; if you move it to a new one, it works as expected

**Comment by Zverik** [comment]
Yeah, I see. Okay, thanks for clarifying :)
