### ISSUE TITLE
Suggestion for multi-sprite-avatar by room support

### ISSUE THREAD

**Issue by bostrt** [seleb/bitsy-hacks#199]
First of all, thanks for these hacks. They've helped me complete a game that wouldn't have otherwise been possible. 

I modified the multi-sprite-avatar hack to change each room. Here's a gist of the changes I've made if you want to take a look. I'm not sure how this would break other hacks so an hesitant to submit a PR. But, I'm curious what you think!

https://gist.github.com/bostrt/fca7cac82c8cfd42be3361e7812bc225

**Comment by seleb** [comment]
hey there, thanks for the snippet! i'll see if there's a way this could be worked into the hacks that would not be disruptive for others, but worst case we can leave this issue open as a reference to point folks towards if they want to do this too

**Comment by seleb** [comment]
just pushed an update with changes to both of these hacks which should allow them to be compatible; lmk if you try it out and have any issues!
