### ISSUE TITLE
getRelativeNumber() don't trim args

### ISSUE THREAD

**Issue by hundun000** [seleb/bitsy-hacks#336]
`getRelativeNumber()` don't trim args. If the arg is number type the `Number()` can handle it; else if it's relatived string, it will miss the `if-case` because the whitespace and return wrong number 0.

reproduction (just `edit room from dialog`  doc's example):
> {draw "type, source, +1, +1, room"}  // will wrong draw at (0, 0)

**Comment by seleb** [comment]
thanks for the bug report, this should be fixed now!
