### ISSUE TITLE
GAme hack

### ISSUE THREAD

**Issue by monkeyboy88570** [seleb/bitsy-hacks#383]
Hey I was just wondering if you could make a hack for the game snow rider 3D?

**Comment by seleb** [comment]
sorry but i think you may be a bit confused, that game does not have anything to do with bitsy

**Comment by jacosadfsafsa** [comment]
YASSSS ADADAYDAYDAY AUGHGHGH

**Comment by nlee33-sketch** [comment]
make a code for roblox bedwar scripts
