### ISSUE TITLE
hackOptions dialog choice?

### ISSUE THREAD

**Issue by zartan9** [seleb/bitsy-hacks#437]
hi i saw in borksy there s an explaination to make dialog choices, but im not sure how to start is there a working html example i can load into bitsy to test? thanks

**Comment by seleb** [comment]
it's pretty old and has more than one hack, but here's an example of a game where i used it: https://seansleblanc.itch.io/salvage-duty

i'm not sure this will be much help if you want to load it into bitsy though, the dialog choices hack only works in the exported game with the hack applied, and will just look like raw text in the bitsy editor

**Comment by zartan9** [comment]
thanks. fun game
